server.port=8080

spring.application.name=gateway-service

spring.cloud.gateway.routes[0].id=customer-route
spring.cloud.gateway.routes[0].uri=http://localhost:8081
spring.cloud.gateway.routes[0].predicates[0]=Path=/customer/**
spring.cloud.gateway.routes[0].filters[0]=RewritePath=/customer/(?<segment>.*), /${segment}

spring.cloud.gateway.routes[1].id=billing-route
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/billing/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/billing/(?<segment>.*), /${segment}

spring.cloud.gateway.filter.request-rate-limiter.enabled=true

management.endpoints.web.exposure.include=*

spring.redis.host=localhost
spring.redis.port=6379

spring.cloud.gateway.routes[0].filters[1]=RequestRateLimiter=redis-rate-limiter(1, 2)
spring.cloud.gateway.routes[0].metadata.request-rate-limiter.key-resolver=#{@ipKeyResolver}
spring.cloud.gateway.routes[0].metadata.request-rate-limiter.redis-rate-limiter.replenishRate=1
spring.cloud.gateway.routes[0].metadata.request-rate-limiter.redis-rate-limiter.burstCapacity=2


spring.cloud.gateway.routes[1].id=billing-service
spring.cloud.gateway.routes[1].uri=http://localhost:8082
spring.cloud.gateway.routes[1].predicates[0]=Path=/billing-api/**
spring.cloud.gateway.routes[1].filters[0]=RewritePath=/billing-api/(?<segment>.*), /$\{segment}
