server.port=8080
spring.application.name=payment-service

resilience4j.circuitbreaker.instances.paymentCircuitBreaker.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.minimumNumberOfCalls=5
resilience4j.circuitbreaker.instances.paymentCircuitBreaker.waitDurationInOpenState=5s

resilience4j.timelimiter.instances.paymentCircuitBreaker.timeoutDuration=2s

management.endpoints.web.exposure.include=*
